build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -29,7 +29,6 @@ jobs:
       - name: Install Linux dependencies
         run: |
           sudo apt-get update
-
           sudo apt-get install -y \
             git \
             zip \
@@ -51,28 +50,50 @@ jobs:
           python -m pip install buildozer
           python -m pip install "cython<3"
 
+      - name: Find project
+        run: |
+          echo "===== REPOSITORY ====="
+          find . -maxdepth 4 -type f | sort
+
+          echo "===== SEARCH BUILDOZER ====="
+
+          SPEC=$(find . -name "buildozer.spec" -type f | head -1)
+
+          if [ -z "$SPEC" ]; then
+            echo "ERROR: buildozer.spec NOT FOUND"
+            exit 1
+          fi
+
+          PROJECT_DIR=$(dirname "$SPEC")
+
+          echo "buildozer.spec found:"
+          echo "$SPEC"
+
+          echo "Project directory:"
+          echo "$PROJECT_DIR"
+
+          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"
+
       - name: Check project
         run: |
           echo "===== PROJECT ====="
-          ls -lah calculator_android
+          ls -lah "$PROJECT_DIR"
 
-          test -f calculator_android/main.py
-          test -f calculator_android/buildozer.spec
+          test -f "$PROJECT_DIR/buildozer.spec"
+          test -f "$PROJECT_DIR/main.py"
 
-          echo "Project is OK"
+          echo "main.py found!"
+          echo "buildozer.spec found!"
 
-      - name: Clean old Android build
+      - name: Clean Buildozer
         run: |
-          rm -rf ~/.buildozer
-          rm -rf calculator_android/.buildozer
-          rm -rf calculator_android/bin
-
-          echo "Old Android build removed"
+          rm -rf "$PROJECT_DIR/.buildozer"
+          rm -rf "$PROJECT_DIR/bin"
 
       - name: Build APK
-        working-directory: calculator_android
         run: |
-          yes | buildozer -v android debug
+          cd "$PROJECT_DIR"
+          buildozer -v android debug
 
       - name: Find APK
         if: always()
@@ -85,5 +106,6 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: calculator-apk
-          path: calculator_android/bin/*.apk
+          path: |
+            **/bin/*.apk
           if-no-files-found: error
